

const SCHEDULES=[
    {
        id:1,
        category:"Cricket",
        image:"https://wallpapercave.com/wp/wp6731464.jpg",
        teamA:"BHU",
        teamB:"BOMBAY",
        venue:"Gymkhana Ground",
        time:"7:00 PM",
    },
    {
        id:2,
        category:"Football",
        image:"https://cdn.wallpapersafari.com/81/18/wQsdIh.png",
        teamA:"BHU",
        teamB:"Roorkee",
        venue:"Gymkhana Ground",
        time:"5:00 PM",
    },
    {
        id:3,
        category:"Basketball",
        image:"https://cdn.wallpapersafari.com/33/63/vOoaMg.jpg",
        teamA:"BHU",
        teamB:"Guwahati",
        venue:"Rajputana Ground",
        time:"6:00 PM",
    },
    {
        id:4,
        category:"Cricket",
        image:"https://wallpapercave.com/wp/wp6731464.jpg",
        teamA:"GOA",
        teamB:"BOMBAY",
        venue:"ADV Ground",
        time:"4:00 PM",
    },
    {
        id:5,
        category:"Basketball",
        image:"https://cdn.wallpapersafari.com/33/63/vOoaMg.jpg",
        teamA:"Hyderabad",
        teamB:"Mandi",
        venue:"Rajputana Ground",
        time:"8:00 PM",
    },
    {
        id:6,
        category:"Badminton",
        image:"https://wallpaperaccess.com/full/1429492.jpg",
        teamA:"BHU",
        teamB:"Dhanbad",
        venue:"Gymkhana Ground",
        time:"7:00 PM",
    },
    {
        id:11,
        category:"Badminton",
        image:"https://wallpaperaccess.com/full/1429492.jpg",
        teamA:"GOA",
        teamB:"DELHI",
        venue:"SAC",
        time:"9:00 PM",
    },
    {
        id:7,
        category:"Football",
        image:"https://cdn.wallpapersafari.com/81/18/wQsdIh.png",
        teamA:"Jodhpur",
        teamB:"Madras",
        venue:"ADV Ground",
        time:"3:00 PM",
    },
    {
        id:8,
        category:"Cricket",
        image:"https://wallpapercave.com/wp/wp6731464.jpg",
        teamA:"DELHI",
        teamB:"BHU",
        venue:"Rajputana Ground",
        time:"6:00 PM",
    },
];

export default SCHEDULES;
